/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2013-2016 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.map;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;

import com.google.android.gms.common.GoogleApiAvailability;
import com.google.android.gms.maps.GoogleMap;
import com.google.android.gms.maps.model.BitmapDescriptorFactory;
import com.google.android.gms.maps.model.JointType;

@Kroll.module(name = "Map", id = "ti.map")
public class MapModule extends KrollModule {
	public static final String PROPERTY_MAP_STYLE = "mapStyle";
	public static final String PROPERTY_DRAGGABLE = "draggable";
	public static final String PROPERTY_POINTS = "points";
	public static final String PROPERTY_TRAFFIC = "traffic";
	public static final String PROPERTY_MAP = "map";
	public static final String PROPERTY_SHAPE = "shape";
	public static final String PROPERTY_SHAPE_TYPE = "shapeType";
	public static final String PROPERTY_NEWSTATE = "newState";
	public static final String PROPERTY_CUSTOM_VIEW = "customView";
	public static final String PROPERTY_PIN = "pin";
	public static final String PROPERTY_INFO_WINDOW = "infoWindow";
	public static final String PROPERTY_LEFT_PANE = "leftPane";
	public static final String PROPERTY_RIGHT_PANE = "rightPane";
	public static final String PROPERTY_SHOW_INFO_WINDOW = "showInfoWindow";
	public static final String PROPERTY_USER_LOCATION_BUTTON = "userLocationButton";
	public static final String PROPERTY_COMPASS_ENABLED = "compassEnabled";
	public static final String PROPERTY_MAP_TOOLBAR_ENABLED = "mapToolbarEnabled";
	public static final String PROPERTY_TILT = "tilt";
	public static final String PROPERTY_BEARING = "bearing";
	public static final String PROPERTY_ZOOM = "zoom";
	public static final String PROPERTY_ZORDER_ON_TOP = "zOrderOnTop";
	public static final String PROPERTY_CENTER_OFFSET = "centerOffset";
	public static final String PROPERTY_PANNING = "panning";
	public static final String PROPERTY_STREET_NAMES = "streetNames";
	public static final String PROPERTY_USER_NAVIGATION = "userNavigation";
	public static final String EVENT_PIN_CHANGE_DRAG_STATE = "pinchangedragstate";
	public static final String EVENT_ON_SNAPSHOT_READY = "onsnapshotready";

	public static final String PROPERTY_STROKE_COLOR = "strokeColor";
	public static final String PROPERTY_STROKE_WIDTH = "strokeWidth";
	public static final String PROPERTY_FILL_COLOR = "fillColor";
	public static final String PROPERTY_ZINDEX = "zIndex";

	public static final String PROPERTY_POLYGON = "polygon";
	public static final String PROPERTY_POLYGONS = "polygons";
	public static final String PROPERTY_POLYLINE = "polyline";
	public static final String PROPERTY_POLYLINES = "polylines";
	public static final String PROPERTY_CIRCLE = "circle";
	public static final String PROPERTY_CIRCLES = "circles";
	public static final String PROPERTY_CENTER = "center";
	public static final String PROPERTY_RADIUS = "radius";
	public static final String PROPERTY_INTERVAL = "interval";

	public static final String PROPERTY_TILE_PROVIDER = "tileProvider";
	public static final String PROPERTY_MBTILES = "mbtiles";
	public static final String PROPERTY_PATTERN = "patternItem";
	public static final String PROPERTY_DASH_LENGTH = "dashLength";
	public static final String PROPERTY_GAP_LENGTH = "gapLength";
	public static final String PROPERTY_JOINT_TYPE = "jointType";
	@Kroll.constant
	public static final String PROPERTY_VERSION = "version";
	@Kroll.constant
	public static final String PROPERTY_CRS = "crs";
	@Kroll.constant
	public static final String PROPERTY_FORMAT = "format";
	@Kroll.constant
	public static final String PROPERTY_LAYER = "layer";
	@Kroll.constant
	public static final String PROPERTY_TYPE = "type";
	
	public static final int JOINT_TYPE_DEFAULT = JointType.DEFAULT;
	public static final int JOINT_TYPE_BEVEL = JointType.BEVEL;
	public static final int JOINT_TYPE_ROUND = JointType.ROUND;
	public static final int TYPE_MARCHING_ANTS = 1;
	@Kroll.constant
	public static final int TYPE_TMS = 0;
	@Kroll.constant
	public static final int TYPE_WMS = 1;
	
	

	public static final String LCAT = "TiMap";

	@Kroll.constant
	public static final int NORMAL_TYPE = GoogleMap.MAP_TYPE_NORMAL;
	@Kroll.constant
	public static final int TERRAIN_TYPE = GoogleMap.MAP_TYPE_TERRAIN;
	@Kroll.constant
	public static final int SATELLITE_TYPE = GoogleMap.MAP_TYPE_SATELLITE;
	@Kroll.constant
	public static final int HYBRID_TYPE = GoogleMap.MAP_TYPE_HYBRID;
	@Kroll.constant
	public static final int NONE_TYPE = GoogleMap.MAP_TYPE_NONE;
	@Kroll.constant
	public static final int MAP_NORMAL_TYPE = GoogleMap.MAP_TYPE_NORMAL;
	@Kroll.constant
	public static final int MAP_TERRAIN_TYPE = GoogleMap.MAP_TYPE_TERRAIN;
	@Kroll.constant
	public static final int MAP_SATELLITE_TYPE = GoogleMap.MAP_TYPE_SATELLITE;
	@Kroll.constant
	public static final int MAP_HYBRID_TYPE = GoogleMap.MAP_TYPE_HYBRID;
	@Kroll.constant
	public static final int MAP_NONE_TYPE = GoogleMap.MAP_TYPE_NONE;
	@Kroll.constant
	public static final int ANNOTATION_DRAG_STATE_START = 0;
	@Kroll.constant
	public static final int ANNOTATION_DRAG_STATE_END = 1;

	@Kroll.constant
	public static final int SUCCESS = 0;
	@Kroll.constant
	public static final int SERVICE_MISSING = 1;
	@Kroll.constant
	public static final int SERVICE_VERSION_UPDATE_REQUIRED = 2;
	@Kroll.constant
	public static final int SERVICE_DISABLED = 3;
	@Kroll.constant
	public static final int SERVICE_INVALID = 9;

	@Kroll.constant
	public static final float ANNOTATION_AZURE = BitmapDescriptorFactory.HUE_AZURE;
	@Kroll.constant
	public static final float ANNOTATION_BLUE = BitmapDescriptorFactory.HUE_BLUE;
	@Kroll.constant
	public static final float ANNOTATION_CYAN = BitmapDescriptorFactory.HUE_CYAN;
	@Kroll.constant
	public static final float ANNOTATION_GREEN = BitmapDescriptorFactory.HUE_GREEN;
	@Kroll.constant
	public static final float ANNOTATION_MAGENTA = BitmapDescriptorFactory.HUE_MAGENTA;
	@Kroll.constant
	public static final float ANNOTATION_ORANGE = BitmapDescriptorFactory.HUE_ORANGE;
	@Kroll.constant
	public static final float ANNOTATION_RED = BitmapDescriptorFactory.HUE_RED;
	@Kroll.constant
	public static final float ANNOTATION_ROSE = BitmapDescriptorFactory.HUE_ROSE;
	@Kroll.constant
	public static final float ANNOTATION_VIOLET = BitmapDescriptorFactory.HUE_VIOLET;
	@Kroll.constant
	public static final float ANNOTATION_YELLOW = BitmapDescriptorFactory.HUE_YELLOW;

	public MapModule() {
		super();
	}

	@Kroll.method
	public int getPlayservicesversionscode() {
		GoogleApiAvailability googleAPI = GoogleApiAvailability.getInstance();
		return GoogleApiAvailability.GOOGLE_PLAY_SERVICES_VERSION_CODE;
	}

	@Kroll.method
	public int isGooglePlayServicesAvailable() {
		GoogleApiAvailability googleAPI = GoogleApiAvailability.getInstance();
		return googleAPI.isGooglePlayServicesAvailable(TiApplication
				.getAppRootOrCurrentActivity());
	}
}
